### ISSUE TITLE
Pull access denied

### ISSUE THREAD

**Issue by erprateek** [ContinuumIO/gtc2019-numba#3]
pull access denied for conda_cuda_base_2019, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I am logged in via dockerhub

**Comment by seibert** [comment]
we haven't pushed these images to docker hub.  You currently have to build them yourself using these directions:

https://github.com/ContinuumIO/gtc2019-numba/tree/master/docker

**Comment by erprateek** [comment]
Didn't communicate this earlier ... 
$ docker build -t numba_gtc2019:latest ./notebooks

> Sending build context to Docker daemon  2.048kB
> Step 1/8 : FROM conda_cuda_base_2019:latest
> pull access denied for conda_cuda_base_2019, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by seibert** [comment]
Ah, looks like I have a typo in the directions, the first docker build should be:

```
docker build -t conda_cuda_base_2019:latest ./base
```

I have fixed it in the README.  Thanks for finding this!

**Comment by erprateek** [comment]
Seems to be working now. Appreciate your response!
